### ISSUE TITLE
Getting in touch

### ISSUE THREAD

**Issue by bfistein** [nulastudio/NULASpider#6]
Hi, I'm from the PeachPie team. Is there a way to get in touch with you guys? Your email is bouncing back. I just want to get a better understanding of what this project does. Thanks!

**Comment by liesauer** [comment]
you can mail me directly, i am in charge of most of the projects. NULASpider is a powerful crawler that provides rich rules so you can crawl a website in a few minutes. and it's high expansibility and built-in callbacks allow you to handle any kind of websites. how ever, we are facing a serious encoding problem for a long time because of the differences of .NET `string` and PHP `string`. `string` in PHP is binary-safe, but in .NET, it's not, it is sanitized. so when you try to store unknown encoding data(or binary data), the data was changed, and can not be restore.

**Comment by bfistein** [comment]
Ok thanks for the info. And the original source code was written in php? Or did you create it as a php/c# hybrid from scratch? Foes the crawler work then or does it not due to the encoding issues?

**Comment by liesauer** [comment]
it was written in php in earlier versions, but due to some limitations of PHP, like multi-thread, the crawler was inefficient, but it worked.  when i found Peachpie, i decided to port it to Peachpie so that i can use the advantages of PHP and .NET both. now, about 15% of codes ware written in c#, most of them are helpers and utils, in order to make something more easier to use in PHP and avoid some peachpie code-generated issues in previous versions of Peachpie. the crawler works fine if target website is `UTF-8`. but we still facing the encoding issues if the target website is using `GBK` `BIG5` `Shift-JIS`, etc.

**Comment by bfistein** [comment]
Very cool, thank you. I can close this for now and hopefully the encoding issues will gradually get resolved in the future.
